source 'https://rubygems.org'

gem 'fluentd', '~>0.14.17'
gem 'fluent-plugin-record-reformer', '~>0.9.0'
gem 'fluent-plugin-systemd', '~>0.0.8'
gem 'fluent-plugin-google-cloud', '~>0.6.3'
gem 'fluent-plugin-detect-exceptions', '~>0.0.5'
gem 'fluent-plugin-prometheus', '~>0.3.0'
gem 'oj', '~>3.0.0'
